services:
  rabbitmq:
    container_name: applications_queue
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - wings-for-the-life
  application-service:
    container_name: application-service
    build:
      dockerfile: Dockerfile-ApplicationService
    ports:
      - 8080:8080
    image: application-service:latest
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - wings-for-the-life
  underwrite-service:
    container_name: underwriter-service
    build:
      dockerfile: Dockerfile-UnderWriterService
    ports:
      - 8081:8081
    image: underwriter-service:latest
    networks:
      - wings-for-the-life
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:14.10
    container_name: postgres
    environment:
      POSTGRES_DB: "applications"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    expose:
      - 5432

networks:
  wings-for-the-life:
    driver: bridge